

document.write('<li class=\"hh_yes\"><a href=\"../index.en.html\" id=\"hhhome\" title=\"home\"></a></li>');
document.write('<li class=\"hh_yes\"><a href=\"../html/sm03.en.html\" id=\"hhsite\" title=\"site map\"></a></li>');


document.write('<li id=\"n-basics\"><a href=\"../01.basics/!rb02.en.html\" class=\"dir\">Basics</a>');
document.write('<ul><li><a href=\"../04.history/hi04.en.html\">Historical Overview</a></li>');
document.write('	<li><a href=\"../01.basics/Physical%20fundamentals%20of%20the%20radar%20principle.en.html\">Physical Bases of Radar</a></li>');
document.write('	<li><a href=\"../01.basics/Radar%20Principle.en.html\">Radar Basic Principle</a></li>');
document.write('	<li><a href=\"../01.basics/Radar%20Principle.en.html\" class=\"dir\">Principle of Measurement</a>');
document.write('	<ul><li class=\"first\"><a href=\"../01.basics/Distance-determination.en.html\">Distance-determination</a></li>');
document.write('	<li><a href=\"../01.basics/Direction-determination.en.html\">Direction-determination</a></li>');
document.write('	<li><a href=\"../01.basics/Maximum%20Unambiguous%20Range.en.html\">Maximum Unambiguous Range</a></li>');
document.write('	<li><a href=\"../01.basics/Minimal%20Measuring%20Range.en.html\">Minimal Measuring Range</a></li>');
document.write('	<li><a href=\"../01.basics/Measurement%20of%20the%20elevation%20angle.en.html\">Elevation Angle</a></li>');
document.write('	<li><a href=\"../01.basics/Range%20Resolution.en.html\">Range Resolution</a></li>');
document.write('	<li><a href=\"../01.basics/Radars%20Accuracy.en.html\">Accuracy</a></li>');
document.write('	</ul></li>');
document.write('	<li><span class=\"dir\">Radar timing performance</span>');
document.write('	<ul><li class=\"first\"><a href=\"../01.basics/Pulse%20Repetition%20Frequency%20%28PRF%29.en.html\">Pulse Repetition Frequency</a></li>');
document.write('	<li><a href=\"../01.basics/Duty%20cycle.en.html\">Duty Cycle</a></li>');
document.write('	<li><a href=\"../01.basics/Dwell%20Time%20and%20Hits%20per%20Scan.en.html\">Dwell Time/ Hits per Scan</a></li>');
document.write('	<li><a href=\"../01.basics/Time-dependences%20in%20Radar.en.html\">Time Consideration of Pulse Radar</a></li>');
document.write('	</ul></li>');
document.write('	<li><span class=\"dir\">The Radar Equation</span>');
document.write('	<ul><li class=\"first\"><a href=\"../01.basics/Free-Space%20Path%20Loss.en.html\">Derivation of Free-Space Path Loss</a></li>');
document.write('	<li><a href=\"../01.basics/The%20Radar%20Range%20Equation.en.html\">Derivation of the Radar Equation</a></li>');
document.write('	<li><a href=\"../01.basics/Radar%20Cross%20Section.en.html\">Radar Cross-Section</a></li>');
document.write('	<li><a href=\"../01.basics/Typical%20Search%20Radar%20Loss%20Budget.en.html\">Radar Loss Budget</a></li>');
document.write('	<li><a href=\"../01.basics/The%20Radar%20equation%20in%20practice.en.html\">Exemplary Calculations</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../07.waves/Waves%20and%20Frequency%20Ranges.en.html\">Radar Frequency Bands</a></li>');
document.write('	<li><a href=\"../01.basics/Radar%20Coverage.en.html\">Radar Coverage</a></li>');
document.write('	<li><a href=\"../16.eccm/ja01.en.html\">Electronic Warfare</a></li>');
document.write('	</ul></li>');

document.write('<li id=\"n-sets\"><a href=\"../02.basics/!rp02.en.html\" class=\"dir\">Radar Sets</a>');
document.write('<ul><li><span class=\"dir\">Classification of Radar systems</span>');
document.write('	<ul><li class=\"first\"><a href=\"../02.basics/Classification%20of%20Radar%20systems%20%281%29.en.html\" class=\"dir\">Depending on Technologies</a>');
document.write('	<ul><li class=\"first\"><a href=\"../01.basics/Radar%20Principle.en.html\">Primary Radar</a></li>');
document.write('	<li><a href=\"../13.ssr/!sr01.en.html\">Secondary Radar</a></li>');
document.write('	<li><a href=\"../02.basics/Continuous%20Wave%20Radar.en.html\">Continuous Wave (CW) Radar</a></li>');
document.write('	<li><a href=\"../02.basics/Frequency%20Modulated%20Continuous%20Wave%20Radar.en.html\">Frequency Modulated CW Radar (FMCW)</a></li>');
document.write('	<li><a href=\"../02.basics/FMiCW%20Radar.en.html\">FMiCW Radar</a></li>');
document.write('	<li><a href=\"../02.basics/Pulse%20Radar.en.html\">Pulse radar</a></li>');
document.write('	<li><a href=\"../05.bistatic/bs04.en.html\">Bistatic Radar</a></li>');
document.write('	<li><a href=\"../20.airborne/ab06.en.html\">Sidelooking Airborne Radar</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../02.basics/Classification%20of%20Radar%20systems%20%282%29.en.html\" class=\"dir\">Depending on Designed Use</a>');
document.write('	<ul><li class=\"first\"><a href=\"../02.basics/Air-Defense%20Radars.en.html\">Air Defense Radar</a></li>');
document.write('	<li><a href=\"../02.basics/ATC-Radars.en.html\">ATC-Radars</a></li>');
document.write('	<li><a href=\"../02.basics/Ground%20penetrating%20radar.en.html\">Ground penetrating radar</a></li>');
document.write('	<li class=\"first\"><a href=\"../15.weather/!wr01.en.html\" class=\"dir\">Weather Radar</a>');
document.write('	<ul><li class=\"first\"><a href=\"../15.weather/wr04.en.html\">Principle of Operation</a></li>');
document.write('	<li><a href=\"../15.weather/wr05.en.html\">Adaptation of the Radar Equation</a></li>');
document.write('	<li><a href=\"../15.weather/wr07.en.html\">Precipitation Radar</a></li>');
document.write('	<li><a href=\"../15.weather/wr08.en.html\">Cloud Radar</a></li>');
document.write('	<li><a href=\"../15.weather/wr09.en.html\">Wind Profiler</a></li>');
document.write('	<li><a href=\"../19.kartei/ka58.en.html\">List of weather radars</a></li>');
document.write('	</ul></li>');
document.write('	</ul></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../19.kartei/ka01.en.html\">Database of Radars</a></li>');
document.write('	<li class=\"first\"><a href=\"../02.basics/didactic%20radars.en.html\" class=\"dir\">Didactic Radars</a>');
document.write('	<ul><li class=\"first\"><a href=\"../19.kartei/13.labs/karte003.en.html\">CW-Radar</a></li>');
document.write('	<li><a href=\"../19.kartei/13.labs/karte004.en.html\">FMCW-Radar</a></li>');
document.write('	<li><a href=\"../19.kartei/13.labs/karte006.en.html\">Pulse Radar DPR–886</a></li>');
document.write('	<li><a href=\"../19.kartei/13.labs/karte007.en.html\">Didactical Noiseradar</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../14.selfmade/!sm01.en.html\">Self-made CW-/FMCW- Radar</a></li>');
document.write('	</ul></li>');

document.write('<li id=\"n-modes\"><a href=\"../05.bistatic/bs02.en.html\" class=\"dir\">Radartechnology</a>');
document.write('	<ul><li class=\"first\"><span class=\"dir\">Frequency Diversity Radar</span>');
document.write('	<ul><li class=\"first\"><a href=\"../01.basics/Frequency%20Diversity%20Radar.en.html\">Functional block diagram</a></li>');
document.write('	<li><a href=\"../01.basics/Fluctuation%20Loss.en.html\">Fluctuation Loss</a></li>');
document.write('	<li><a href=\"../01.basics/Radar%20equation%20for%20frequency%20diversity%20radar.en.html\">Adaptation of the Radar Equation</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../15.weather/wr51.en.html\">Polarimetric Radar</a></li>');
document.write('	<li><a href=\"../08.transmitters/Intrapulse%20Modulation.en.html\">Intrapulse Modulation</a></li>');
document.write('	<li><a href=\"../20.airborne/ab07.en.html\">Synthetic Aperture Radar</a></li>');

document.write('	<li><a href=\"../13.ssr/!sr01.en.html\" class=\"dir\">Secondary Radar</a>');
document.write('	<ul><li class=\"first\"><a href=\"../13.ssr/sr04.en.html\">Functional Block Diagram</a></li>');
document.write('	<li><a href=\"../13.ssr/sr05.en.html\" class=\"dir\">Mode A/C</a>');
document.write('	<ul><li class=\"first\"><a href=\"../13.ssr/sr06.en.html\">Mode A/C Uplink Formats</a></li>');
document.write('	<li><a href=\"../13.ssr/sr07.en.html\">Reply (Downlink) Format</a></li>');
document.write('	<li><a href=\"../13.ssr/sr09.en.html\">Side Lobe Suppression</a></li>');
document.write('	<li><a href=\"../13.ssr/sr14.en.html\">Fruit</a></li>');
document.write('	<li><a href=\"../13.ssr/sr15.en.html\">Garbling</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../13.ssr/sr20.en.html\" class=\"dir\">Mode S</a>');
document.write('	<ul><li class=\"first\"><a href=\"../13.ssr/sr21.en.html\">Mode S Interrogations</a></li>');
document.write('	<li><a href=\"../13.ssr/sr22.en.html\">Individually Mode S Interrogation</a></li>');
document.write('	<li><a href=\"../13.ssr/sr23.en.html\">Differential Phase Shift Keying (DPSK)</a></li>');
document.write('	<li><a href=\"../13.ssr/sr24.en.html\">Reply Formats</a></li>');
document.write('	<li><a href=\"../13.ssr/sr25.en.html\">Squitter Mode</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../13.ssr/sr17.en.html\">Transponder</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../02.basics/MIMO-radar.en.html\">MIMO - Radar</a></li>');
document.write('	</ul></li>');

document.write('<li id=\"n-devices\"><a href=\"../06.antennas/!an02.en.html\" class=\"dir\">Radar Devices</a>');
document.write('	<ul><li class=\"first\"><a href=\"../06.antennas/!an01.en.html\" class=\"dir\">Antenna</a>');
document.write('	<ul><li class=\"first\"><a href=\"../06.antennas/Antenna%20Characteristics.en.html\">Characteristics</a></li>');
document.write('	<li><a href=\"../06.antennas/Parabolic%20Antenna.en.html\">Parabolic Dish Antenna</a></li>');
document.write('	<li><a href=\"../06.antennas/Slot%20Antenna.en.html\">Slot Antenna</a></li>');
document.write('	<li><a href=\"../06.antennas/Cosecant%20Squared%20Pattern.en.html\">Cosecant Squared Pattern</a></li>');
document.write('	<li><a href=\"../06.antennas/Cassegrain%20Antenna.en.html\">Cassegrain Antenna</a></li>');
document.write('	<li><span class=\"dir\">Phased Array Antenna</span>');
document.write('	<ul><li class=\"first\"><a href=\"../06.antennas/Phased%20Array%20Antenna.en.html\">Principle of Operation</a></li>');
document.write('	<li><a href=\"../06.antennas/Feeding%20Systems.en.html\">Feeding Systems</a></li>');
document.write('	<li><a href=\"../06.antennas/Crow%27s-Nest%20Antenna.en.html\">Crow\'s-Nest Antenna</a></li>');
document.write('	<li><a href=\"../06.antennas/Phase%20Shifter.en.html\">Phase Shifter Devices</a></li>');
document.write('	<li><a href=\"../06.antennas/an80.en.html\">Phased-Array Demonstrator</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../06.antennas/Monopulse%20Antenna.en.html\">Monopulse Antenna</a></li>');
document.write('	<li><a href=\"../08.transmitters/Transmitter%20Modules%20of%20an%20Active%20Antenna.en.html\">Active Antenna</a></li>');
document.write('	<li><a href=\"../06.antennas/Duplexer.en.html\">Duplexer</a></li>');
document.write('	<li><a href=\"../06.antennas/Diplexer-Filter.en.html\">Diplexer</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../08.transmitters/!tx01.en.html\" class=\"dir\">Transmitter</a>');
document.write('	<ul><li><a href=\"../08.transmitters/Radar%20Transmitter.en.html\">Overview</a></li>');
document.write('	<li class=\"first\"><span class=\"dir\">Coherent-on-Receive Radar</span>');
document.write('	<ul><li class=\"first\"><a href=\"../08.transmitters/Pseudo-coherent%20Radar.en.html\">Functional Block Diagram</a></li>');
document.write('	<li><a href=\"../08.transmitters/Radar%20Modulator.en.html\">Modulator</a></li>');
document.write('	<li><a href=\"../08.transmitters/Thyratron.en.html\">Thyratron</a></li>');
document.write('	<li><a href=\"../08.transmitters/Magnetron.en.html\">Magnetron</a></li>');
document.write('	</ul></li>');
document.write('	<li><span class=\"dir\">Coherent Radar</span>');
document.write('	<ul><li class=\"first\"><a href=\"../11.coherent/co05.en.html\">Concept of Coherence</a></li>');
document.write('	<li><a href=\"../08.transmitters/Fully%20Coherent%20Radar.en.html\">Functional Block Diagram</a></li>');
document.write('	<li><a href=\"../08.transmitters/Crossed-Field%20Amplifier%20%28Amplitron%29.en.html\">Cross-Field Amplifier</a></li>');
document.write('	<li><a href=\"../08.transmitters/Klystron.en.html\">Klystron</a></li>');
document.write('	<li><a href=\"../08.transmitters/Extended%20Interaction%20Klystron.en.html\">Extended Interactive Klystron</a></li>');
document.write('	<li><a href=\"../08.transmitters/Traveling%20Wave%20Tube.en.html\">Traveling-wave tube</a></li>');
document.write('	<li><a href=\"../08.transmitters/twystron.en.html\">Twystron</a></li>');
document.write('	<li><a href=\"../08.transmitters/Solid%20State%20Amplifier.en.html\">solid-state Amplifier</a></li>');
document.write('	<li><a href=\"../08.transmitters/Transmitter%20Modules%20of%20an%20Active%20Antenna.en.html\">Transmitter Modules of Active Antennas</a></li>');
document.write('	</ul></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../09.receivers/!rx01.en.html\" class=\"dir\">Receiver</a>');
document.write('	<ul><li class=\"first\"><span class=\"dir\">Superheterodyne</span>');
document.write('	<ul><li class=\"first\"><a href=\"../09.receivers/rx05.en.html\">Functional Block Diagram</a></li>');
document.write('	<li><a href=\"../09.receivers/rx06.en.html\">Image-Frequency Interferences</a></li>');
document.write('	<li><a href=\"../09.receivers/rx07.en.html\">Double Heterodyning</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../09.receivers/rx08.en.html\">Automatic Gain Control Methods</a></li>');
document.write('	<li><a href=\"../09.receivers/rx11.en.html\">Automatic Frequency Control</a></li>');
document.write('	<li><a href=\"../09.receivers/rx12.en.html\">Amplitude Detector</a></li>');
document.write('	<li><a href=\"../11.coherent/!co01.en.html\" class=\"dir\">Coherent Radar Technology</a>');
document.write('	<ul><li class=\"first\"><a href=\"../11.coherent/co04.en.html\">Clutter</a></li>');
document.write('	<li><a href=\"../11.coherent/co06.en.html\">Doppler Effect</a></li>');
document.write('	<li><a href=\"../11.coherent/co07.en.html\">Pulse Pair Processing</a></li>');
document.write('	<li><a href=\"../11.coherent/Doppler-Filter.en.html\">Doppler Filter</a></li>');
document.write('	<li><a href=\"../11.coherent/co13.en.html\">Blind Speed</a></li>');
document.write('	</ul></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../12.scopes/!sc01.en.html\" class=\"dir\">Radar Scopes</a>');
document.write('	<ul><li class=\"first\"><a href=\"../12.scopes/sc05.en.html\">A-scope</a></li>');
document.write('	<li><a href=\"../12.scopes/sc06.en.html\">B-scope</a></li>');
document.write('	<li><a href=\"../12.scopes/sc11.en.html\">PPI-scope</a></li>');
document.write('	<li><a href=\"../12.scopes/sc13.en.html\">Raster-Scan Monitor</a></li>');
document.write('	</ul></li>');
document.write('	<li><a href=\"../10.processing/sp05.en.html\" class=\"dir\">Radar Signal Processing</a>');
document.write('	<ul><li class=\"first\"><a href=\"../10.processing/sp06.en.html\">I&amp;Q Phase Detector</a></li>');
document.write('	<li><a href=\"../10.processing/sp08.en.html\">Hit Processor</a></li>');
document.write('	<li><a href=\"../10.processing/sp11.en.html\">Sliding Window</a></li>');
document.write('	<li><a href=\"../10.processing/sp13.en.html\">Center of Mass Correlation</a></li>');
document.write('	<li><a href=\"../10.processing/sp20.en.html\">Local Tracking</a></li>');
document.write('	</ul></li>');
document.write('	</ul></li>');

document.write('<li id=\"n-service\"><a href=\"../html/se02.en.html\" class=\"dir\">Service</a>');
document.write('	<ul><li class=\"first\"><a href=\"../html/help.en.html\">Help</a></li>');
document.write('	<li><a href=\"../html/author.en.html\">About us</a></li>');
document.write('	<li><a href=\"../html/data.en.html\">Privacy policy</a></li>');
document.write('	<li><a href=\"../html/sm03.en.html\" class=\"dir\">Sitemap</a>');
document.write('	<ul><li class=\"first\"><a href=\"'+pfad+'03.en.html\">(in Sub Directory)</a></li></ul></li>');
document.write('	<li><a href=\"../druck/index.html\">Print Versions</a></li>');
document.write('	<li><a href=\"../html/html04.en.html\">Suggested Literature</a></li>');
document.write('	<li><a href=\"../html/feed.en.html\">Keyword Register</a></li>');
document.write('	<li><a href=\"../html/abbr.en.html\">List of abbreviations</a></li>');
document.write('	<li><a href=\"../logos/hersteller.html\">Radarmanufacturers Index</a></li>');
document.write('	<li><a href=\"../html/statistik.en.html\">Daily Traffic</a></li>');
document.write('	<li><span class=\"dir\">Appendices</span>');
document.write('	<ul><li class=\"first\"><a href=\"../22.messpraxis/!mp01.en.html\">Measurement practice</a></li>');
document.write('	<li><a href=\"../21.semiconductors/!hl01.en.html\">Semiconductors</a></li>');
document.write('	<li><a href=\"../07.waves/wa01.en.html\">Propagation of Electromagnetic Waves</a></li>');
document.write('	<li><a href=\"../03.linetheory/!tl01.en.html\">Characteristics of Transmission Lines</a></li>');
document.write('	<li><a href=\"../18.explanations/ex49.en.html\">Metric Measurement Units</a></li>');
document.write('	</ul></li>');
document.write('	</ul></li>');
